#!/usr/bin/env bash

set -e

SRC=$1
FILE_LOCAL=$2

file="$SRC/$FILE_LOCAL"

# replace '/' with '\/'
dir_escaped=$(dirname $file | sed 's/\//\\\//g')

cat $file \
    | grep '^%include' \
    | sed "s/%include \"\\(.*\\)\"/$dir_escaped\/\\1/g" \
    | tr '\n' ' '
