#!/usr/bin/env bash

set -e

FILE=$1

# replace `/` with `\/` for `sed`
dir_escaped=$(dirname $FILE | sed 's/\//\\\//g')

cat $FILE \
    | grep '^%include' \
    | sed "s/%include \"\\(.*\\)\"/$dir_escaped\/\\1/g" \
    | tr '\n' ' '
